services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft

    ports:
      - "25565:25565"

    environment:
      EULA: "TRUE"

      TYPE: "FABRIC"
      VERSION: "26.1.2"

      MEMORY: "16G"

      UID: "1001"
      GID: "988"

      USE_AIKAR_FLAGS: "false"
      JVM_OPTS: >-
        -Xms16G
        -Xmx16G
        -XX:+UseG1GC
        -XX:+ParallelRefProcEnabled
        -XX:MaxGCPauseMillis=200
        -XX:+UnlockExperimentalVMOptions
        -XX:+DisableExplicitGC
        -XX:+AlwaysPreTouch
        -XX:G1HeapRegionSize=16M
        -XX:G1ReservePercent=20
        -XX:G1NewSizePercent=30
        -XX:G1MaxNewSizePercent=40
        -XX:G1MixedGCCountTarget=4
        -XX:InitiatingHeapOccupancyPercent=15
        -XX:G1MixedGCLiveThresholdPercent=90
        -XX:G1RSetUpdatingPauseTimePercent=5
        -XX:SurvivorRatio=32
        -XX:+PerfDisableSharedMem
        -XX:MaxTenuringThreshold=1

    volumes:
      - /srv/minecraft:/data

    restart: unless-stopped

    tty: true
    stdin_open: true
